name: Build iOS Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Theos
        run: brew install theos
      
      - name: Build and Package
        run: |
          cd DIMProgress-Source
          export THEOS=/opt/theos
          make clean
          make
          make package
      
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: DIMProgress-deb
          path: DIMProgress-Source/packages/*.deb
